use proj4;

drop table if exists products;

CREATE TABLE products(
 sku                char(9)  NOT NULL PRIMARY KEY,
 category           varchar(50)    NULL,           
 title              varchar(100)   NULL,           
 short_description  varchar(500)   NULL,           
 long_description   varchar(1000)  NULL,           
 cost               decimal(6,2)   NULL,           
 retail             decimal(6,2)   NULL);           

INSERT INTO products VALUES('1J94K63Y9',  'Brittles and toffies',  'Toffee-ettes', 'Danish butter toffee, covered with chocolate and almonds.', 'Irresistible bite-size pieces of rich Danish butter toffee with whole almonds are smothered in Bertha''s creamy milk chocolate, then covered with bits of toasted almonds. Keep a canister on hand for unexpected guests or take one to the office.  1 lb.',  7.25, 16.50  );
INSERT INTO products VALUES('1O94G76Q9',  'Brittles and toffies',  'Hanukkah Peanut Brittle',                   'Classic peanut brittle from an old family recipe.', 'The recipe created by our founder''s mother is a closely guarded secret, but we can tell you that it''s made with creamery butter and plenty of crunchy peanuts. It''s a kosher treat your family and friends will cherish throughout the holiday.  1 lb.',  6.25, 14.50  );
INSERT INTO products VALUES('1U77T63C9',  'Brittles and toffies',  'Sugar Free Peanut Brittle',                 'Our classic peanut brittle, but without sugar.', 'It has the same look and taste as our traditional Peanut Brittle - you won''t be able to tell the difference! Bertha''s Sugar Free Peanut Brittle is scrumptious, sweet and crunchy with the same high quality taste that you''ve come to love from Bertha''s.  1 lb.',  8.25, 18.50  );
INSERT INTO products VALUES('1W96T63B8',  'Brittles and toffies',  'Peanut Butter Brittle Bar',                 'Delicious peanut brittle and rich, creamy milk chocolate.', 'It''s the perfect combination of our famous, old-fashioned, crunchy peanut brittle and rich, creamy milk chocolate. The perfect snack and party treat. Eight individually wrapped 1 oz. bars per box  8 oz.',  4.25,  9.50  );
INSERT INTO products VALUES('2K35T93T5',  'Truffles',              'Pecan Pie Truffles',                        'Rich buttercream with pecans, covered with white chocolate.', 'Our Pecan Pie Truffles start with a rich buttercream filling with only the freshest pecan pieces folded in, then they''re surrounded by Bertha''s white chocolate and topped with an extra large pecan half.  1 lb.', 11.25, 24.00  );
INSERT INTO products VALUES('2L65T93T5',  'Truffles',              'White Chocolate Mint Truffles',             'Delicous white truffles for the holidays.', 'It''s the perfect indulgence for after dinner, to serve alongside coffee or dessert, or for a sweet treat any time of day. You''ll adore the silky-smooth taste as much as the gift-ready packaging.  1 lb.',  9.25, 20.00  );
INSERT INTO products VALUES('2U85T93Z5',  'Truffles',              'Cranberry Orange Truffles',                 'A chocolate truffle filled with orange-cranberry goodness.', 'This stylish truffle bursts with flavor! The center, a fusion of airy white chocolate, citrusy orange and real cranberry pieces is enrobed in Bertha''s rich, luscious dark chocolate and finished with delicate striping. The result? An after dinner flavor sensation your guests are guaranteed to applaud.  1 lb.',  9.25, 20.00  );
INSERT INTO products VALUES('33X98P89N',  'Nuts and chews',        'Polar Bear Paws',                           'Peanuts and caramel in white chocolate', 'This unique piece is a fan favorite! A delicious combination of roasted and salted peanuts and buttery caramel enrobed in white chocolate - what a wonderful treat  1 lb.',  8.90, 20.00  );
INSERT INTO products VALUES('35E94Y99P',  'Nuts and chews',        'Awesome Nut and Chew Bars',                 'Chewy, cruncy, delicious!', 'Our Nut and Chew bars are made with the freshest nuts, and the most delicious caramel.  Much more than a candy bar 8 oz.',  1.75,  3.95  );
INSERT INTO products VALUES('35J74Y99W',  'Nuts and chews',        'Walnut Squares',                            'Walnuts and chocolate in a square bar', 'Loaded with fresh English walnut, these squares have a big chocolate flavor. A deliciously different treat 8 oz.',  1.80,  3.95  );
INSERT INTO products VALUES('35Q94Y73F',  'Nuts and chews',        'Old Fashion Fudge',                         'Delicious old-time fudge assortment.', 'Old fashion fudge, creamy and smooth with nuts.  A variety of our delicious chocolate, peanut butter, and vanilla fudge.  The best fudge you''ve ever eaten 1 lb.',  9.75, 19.95  );
INSERT INTO products VALUES('39J98Q99N',  'Nuts and chews',        'Salted Mixed Nuts',                         'Fresh Roasted, lightly salted nuts', 'This delicious mix oincludes cashews, almonds, hazelnuts, and walnuts.  The freshest nuts available.  No peanuts.  8 oz.',  3.30,  8.50  );
INSERT INTO products VALUES('3J84P89P3',  'Nuts and chews',        'Milk Butter Chews',                         'Rich, creamy caramel enrobbed in delicious milk chocolate', 'This is a caramel lovers dream come true. The perfect texture and chewiness. The perfect mix of buttery salty-sweetness.  It just melts in your mouth  1 lb.',  8.75, 20.00  );
INSERT INTO products VALUES('3R94P89Q7',  'Nuts and chews',        'Pecan clusters',                            'Rich, creamy caramel with pecans in delicious milk chocolate', 'These little jewels will bring a moment of joy into the most ordinary day. Clusters of pure, fresh pecans are nestled in vanilla caramel and drenched in milk chocolate. Bring these out at a party or get-together and watch them quickly disappear.  1 lb.', 10.25, 24.50  );
INSERT INTO products VALUES('54X99B43C',  'Milk chocolate',        'Classic Milk Chocolate Assortment',         'An assortment of our delicious milk chocolates', 'One of our best sellers, this box features an assortment of our most popular milk chocolate candies.  1 lb.',  9.30, 18.95  );
INSERT INTO products VALUES('55P99Y43A',  'Milk chocolate',        'Milk Chocolate Bar',                        'Our exceptional chocolate in a bar.', 'Our famous milk chocolate in a candy bar.  Perfect for cooking or baking, but equally delicious as they are. 15 oz.',  3.57,  8.95  );
INSERT INTO products VALUES('55P99Y43B',  'Milk chocolate',        'Milk Chocolate Bar',                        'Our exceptional chocolate in a bar.', 'The larger size of our famous milk chocolate in a candy bar.  Perfect for cooking or baking, but equally delicious as they are. 32 oz (2 lbs).',  7.00, 15.95  );
INSERT INTO products VALUES('55Q99Y43A',  'Milk chocolate',        'Milk Chocolate Turtles',                    'Caramel and pecans enrobed in our exceptional milk chocolate.', 'We take the creamiest, most delicious caramel, add a generous portion of fresh pecans, then dip in our famous milk chocolate.  A delicious treat that everyone will enjoy. 1 lb.', 11.25, 24.95  );
INSERT INTO products VALUES('55Q99Y73C',  'Milk chocolate',        'Milk Chocolate Creams',                     'Creamy centers enrobed in our exceptional milk chocolate.', 'With the freshest natural ingredents, we create delicious creamy centers and then dip in our famous milk chocolate.  A perennial favorite. 1 lb.',  9.75, 19.95  );
INSERT INTO products VALUES('55X99B43E',  'Milk chocolate',        'Large Classic Milk Chocolate Assortment',   'An assortment of our delicious milk chocolates, in the larger size.', 'One of our best sellers, this larger box features an assortment of our most popular milk chocolate candies.  2.5 lbs.', 23.25, 44.95  );
INSERT INTO products VALUES('84X99B43C',  'Dark chocolate',        'Classic Dark Chocolate Assortment',         'An assortment of our delicious dark chocolates', 'One of our best sellers, this box features an assortment of our most popular dark chocolate candies.  1 lb.',  9.30, 18.95  );
INSERT INTO products VALUES('85P99Y43A',  'Dark chocolate',        'Dark Chocolate Bar',                        'Our exceptional dark chocolate in a bar.', 'Our famous dark chocolate in a candy bar.  Semi-sweet dark chocolate with 80% cacao.  Perfect for cooking or baking, but equally delicious as they are. 15 oz.',  3.57,  8.95  );
INSERT INTO products VALUES('85P99Y43B',  'Dark chocolate',        'Dark chocolate Bar',                        'Our exceptional chocolate in a bar.', 'The larger size of our famous dark chocolate in a candy bar.  Semi-sweet dark chocolate with 80% cacao.  Perfect for cooking or baking, but equally delicious as they are. 32 oz (2 lbs).',  7.00, 15.95  );
INSERT INTO products VALUES('85Q99Y43A',  'Dark chocolate',        'Dark Chocolate Turtles',                    'Caramel and pecans enrobed in our exceptional rich, decadent dark chocolate.', 'We take the creamiest, most delicious caramel, add a generous portion of fresh pecans, then dip in our famous dark chocolate.  A delicious treat that everyone will enjoy. 1 lb.', 11.25, 24.95  );
INSERT INTO products VALUES('85Q99Y73C',  'Dark chocolate',        'Dark Chocolate Creams',                     'Creamy centers enrobed in our exceptional dark chocolate.', 'With the freshest natural ingredents, we create delicious creamy centers and then dip in our famous dark chocolate.  A perennial favorite. 1 lb.',  9.75, 19.95  );
INSERT INTO products VALUES('85X99B43E',  'Dark chocolate',        'Large Classic Dark Chocolate Assortment',   'An assortment of our delicious dark chocolates, in the larger size.', 'One of our best sellers, this larger box features an assortment of our most popular dark chocolate candies.  2.5 lbs.', 23.25, 44.95  );
INSERT INTO products VALUES('8G42K77D3',  'Holiday assortments',  'Christmas Tote',                            'Bertha''s Tote Bag, filled with goodies.', 'If you''re going to tote something around this Christmas, it might as well be Bertha''s candy! We decorated this cute little bag with a gingerbread house that looks good enough to eat! Then we filled it with Bertha''s traditional candy canes, Lollypops and, of course, a Milk Chocolate Santa. Keep the tote once the candy is gone for a Christmas memento or decoration.  5 oz',  3.15,  6.90  );
INSERT INTO products VALUES('8I96H86E4',  'Holiday assortments',  'Chocolate Santa Trio',                      'Three milk chocolate Santas.', 'Beautiful inside and out, Bertha''s Milk Chocolate Santa delivers a holiday dream in every bite. You''ll agree, it''s the only chocolate good enough for St. Nick''s seal of approval!  3 x 5.5 oz',  6.85, 14.50  );
INSERT INTO products VALUES('8P39L86W6',  'Holiday assortments',  'Red Snowflake Fancy',                       'An exquisite holiday assortment.', 'This sparkling red and silver snowflake box is packed with one pound of our most popular holiday confections. Featuring our Divinity Puff, Cashew Brittle, Truffles, milk, dark and white chocolates. An impressive gift for under $20. 1 lb',  8.45, 19.00  );
INSERT INTO products VALUES('8Y29L37E5',  'Holiday assortments',  'Sour Stars',                                'A kids'' favorite, sour and chewy.', 'Sweet, sour and chewy, our Sour Stars have that extreme flavor kids love. Star-shaped jellies in sour cherry red and sour apple green make great stocking stuffers, party treats and candy dish surprises. 8 oz',  2.45,  6.00  );
INSERT INTO products VALUES('8Y39K86V4',  'Holiday assortments',  'Christmas Ornament Fancy',                  'An exquisite holiday assortment.', 'An exquisite package for the most exquisite candy. Tenderly hand-packed chocolates in a holiday assortment of nuts, buttercreams and chews made with the finest nuts and grade AA butter and cream. Two Milk Chocolate Butters are topped with red poinsettias for the holidays. The show-stopping box is Christmas red featuring a trio of antiqued decorative ornaments detailed with flocking and stamped gold foil. 1 1/2 lbs', 18.45, 42.00  );
INSERT INTO products VALUES('8Z29Q84C5',  'Holiday assortments',  'The Chocolate Sampler Pack',                'A selection of Bertha''s holiday favorites.', 'Our very best gift. 7 pounds of Bertha''s very best chocolates and candies. This basket includes 2 lb. Gold Fancy, 8 oz. Molasses Chips, 8 oz. Peppermints, 1 lb. Toffee-ettes, 8 oz. Truffles and 4 oz. Butterscotch Little Pops, 10 oz. Peanut Brittle, 8 pack of Awesome Nut & Chew Bars, 12 pack box of Lollypops and a 4 pack of Classic Candy Bars. This is the perfect gift for any family, office or large group.', 28.30, 65.00  );
INSERT INTO products VALUES('9Q34N66P3',  'Gifts',                'Autumn Assortment',                         'An selection of our delicious fall treats.', 'The classic fall, two-piece gift box is packed to the brim with one pound of Assorted Chocolates, Bertha''s crunchy and buttery Peanut Brittle, rich Molasses Chips and Butterscotch Little Pops. This elegant reusable box will definitely be appreciated by the hostess of any fall gathering.', 17.25, 39.00  );
INSERT INTO products VALUES('9Q35N88P6',  'Gifts',                'Winter Wonderland Box',                     'A collection of delicious Christmas candies.', 'This box of candy is made especially for your favorite little Christmas wonders! It''s extra special because we''ve included flavors especially for the young - and young at heart! - like Scotchmallow and Butterscotch Square. Milk Chocolate Foil Balls are also nestled inside. A sweet gift for children of all ages.',  6.95,  3.20  );
INSERT INTO products VALUES('9U39J36R3',  'Gifts',                'Fall Harvest Box',                          'An selection of our autumn favorites.', 'Miniature but oh-so memorable! You''ll find dozens of reasons to give this 4 x 6 sampler of goodies-great for game-night prizes, or we appreciate you presents for volunteers. You''ll want to keep one at home for drop-in guests, too! Inside this pretty box are Molasses Chips, solid Milk Chocolate Foil Balls, Scotchmallow, Dark Chocolate Chip Truffle, Milk Chocolate Butter and Butterscotch Square. 5 oz',  2.45,  6.50  );
INSERT INTO products VALUES('9Z34M45A3',  'Gifts',                'Autumn Fancy',                              'An assortment of delicious chocolates in a decorated box.', 'From its richly patterned presentation box to the decorative leaf, this gift is exquisite. Nothing but the best will do inside as well. You''ll be dazzled by foil-wrapped chocolate leaves. a selection of our celebrated chocolates, the Truffles everyone loves, and our special Maple Walnut confection. After savoring the chocolates, the box makes a pretty container for jewelry or photos.  12 oz.',  7.25, 14.90  );  








